gemini.api.key=${GEMINI_API_KEY:default_value_for_demo}


gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent



interswitch.api.url=${INTERSWITCH_URL:https://sandbox.interswitch.com}