
server.port=8080

# Interswitch Configurations
interswitch.api.url=${INTERSWITCH_URL:https://qa.interswitchng.com}
interswitch.token.url=${INTERSWITCH_TOKEN_URL:https://qa.interswitchng.com/passport/oauth/token}
interswitch.identity.api.url=${INTERSWITCH_IDENTITY_URL:https://qa.interswitchng.com}
interswitch.client.id=${INTERSWITCH_CLIENT_ID:sandbox_id}
interswitch.client.secret=${INTERSWITCH_CLIENT_SECRET:sandbox_secret}

# Gemini API Configuration
gemini.api.key=${GOOGLE_API_KEY:default_value_for_demo}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
#gemini.vertex.project-id=${GOOGLE_CLOUD_PROJECT:}
#gemini.vertex.location=${GOOGLE_CLOUD_LOCATION:us-central1}
#gemini.vertex.model=${GEMINI_MODEL:gemini-1.5-flash-001}
spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=aurascore
mono.secret.key=${MONO_SECRET_KEY:dummy_key}


GOOGLE_API_KEY=${GOOGLE_API_KEY}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration